name: CI

# Run on PR
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make docs-build
